### DGWO Procedure

In [1]:
import numpy as np

In [2]:
n_dptos = 7

In [3]:
dptos = np.arange(1, n_dptos+1)
dptos = np.random.permutation(dptos)
dptos

array([5, 2, 1, 6, 3, 7, 4])

In [4]:
bahias = np.random.randint(0, 2, n_dptos-1)
bahias = np.append(bahias, 1)
bahias

array([1, 0, 0, 0, 0, 1, 1])

In [5]:
# Set parameters M, teta1, teta2
M = 10
theta_1 = 0.3
theta_2 = 0.5

### Iniciar manada y evaluar su funcion fitness

In [6]:
manada = []
fit_manada = []

for i in range(M):
    lobo_dp = np.random.permutation(dptos) # Componente permutacion - departamentos
    lobo_bh = np.random.randint(0, 2, n_dptos-1) # Componente binario - bahias
    lobo_bh = np.append(lobo_bh, 1) # Bahias debe terminar en 1
    lobo = [lobo_dp, lobo_bh]
    fit_lb = np.random.randint(20, 100) # metodo calcular_fitness()
    
    manada.append(lobo)
    fit_manada.append(fit_lb)

In [7]:
manada

[[array([4, 5, 1, 3, 2, 7, 6]), array([0, 1, 1, 0, 1, 1, 1])],
 [array([4, 1, 5, 7, 2, 3, 6]), array([0, 1, 1, 1, 1, 1, 1])],
 [array([3, 4, 7, 1, 2, 6, 5]), array([1, 1, 1, 0, 0, 1, 1])],
 [array([2, 4, 6, 7, 3, 1, 5]), array([1, 0, 1, 0, 0, 0, 1])],
 [array([5, 2, 7, 4, 6, 3, 1]), array([1, 0, 0, 1, 1, 1, 1])],
 [array([4, 7, 3, 2, 6, 1, 5]), array([1, 0, 1, 0, 0, 0, 1])],
 [array([1, 4, 7, 3, 6, 5, 2]), array([0, 0, 0, 0, 0, 0, 1])],
 [array([7, 4, 6, 2, 1, 5, 3]), array([0, 1, 1, 1, 0, 0, 1])],
 [array([7, 6, 4, 5, 2, 1, 3]), array([1, 1, 0, 0, 0, 0, 1])],
 [array([4, 3, 2, 6, 7, 1, 5]), array([1, 0, 1, 1, 1, 0, 1])]]

In [8]:
fit_manada

[26, 79, 25, 42, 92, 61, 29, 53, 82, 65]

### Identificacion de lobos lideres: alpha, beta y delta

In [9]:
lobos_lideres = [] # alpha, beta, delta
fit_lideres = []

In [10]:
while len(lobos_lideres) < 3:
    pos_min = np.argmin(fit_manada) # Identificar el lobo con min fitness
    lider = manada[pos_min]
    fit_lider = fit_manada[pos_min]
    manada.pop(pos_min) # Sacarlo de la manada
    fit_manada.pop(pos_min)
    
    lobos_lideres.append(lider) # Anadir a los lideres
    fit_lideres.append(fit_lider)

In [11]:
lobos_lideres

[[array([3, 4, 7, 1, 2, 6, 5]), array([1, 1, 1, 0, 0, 1, 1])],
 [array([4, 5, 1, 3, 2, 7, 6]), array([0, 1, 1, 0, 1, 1, 1])],
 [array([1, 4, 7, 3, 6, 5, 2]), array([0, 0, 0, 0, 0, 0, 1])]]

In [12]:
fit_lideres

[25, 26, 29]

In [13]:
len(manada)

7

### Comportamiento de busqueda

In [14]:
manada

[[array([4, 1, 5, 7, 2, 3, 6]), array([0, 1, 1, 1, 1, 1, 1])],
 [array([2, 4, 6, 7, 3, 1, 5]), array([1, 0, 1, 0, 0, 0, 1])],
 [array([5, 2, 7, 4, 6, 3, 1]), array([1, 0, 0, 1, 1, 1, 1])],
 [array([4, 7, 3, 2, 6, 1, 5]), array([1, 0, 1, 0, 0, 0, 1])],
 [array([7, 4, 6, 2, 1, 5, 3]), array([0, 1, 1, 1, 0, 0, 1])],
 [array([7, 6, 4, 5, 2, 1, 3]), array([1, 1, 0, 0, 0, 0, 1])],
 [array([4, 3, 2, 6, 7, 1, 5]), array([1, 0, 1, 1, 1, 0, 1])]]

In [15]:
fit_manada

[79, 42, 92, 61, 53, 82, 65]

In [16]:
tam_mov = np.floor(n_dptos * theta_1).astype(int) # Tamano del movimiento a realizar (e.g. 2 posiciones)

for ind, lobo in enumerate(manada):
    pos_ini = np.random.randint(0, n_dptos + 1 - tam_mov) # Indice inicial del movimiento (e.g. indice 1)
    pos_fin = np.random.randint(0, n_dptos + 1 - tam_mov) # Indice en donde se movera la posicion (e.g. indice 4)
    pos_mov = np.arange(pos_ini, pos_ini + tam_mov) # Indices del movimiento a realizar (e.g. [1, 2])
    
    # Movimiento para el elemento de departamentos
    dp = lobo[0]
    mov_dp = dp[pos_mov]
    dp = np.delete(dp, pos_mov)
    dp = np.insert(dp, pos_fin, mov_dp)
    
    # Movimiento para el elemento de bahias
    bh = lobo[1]
    mov_bh = bh[pos_mov]
    bh = np.delete(bh, pos_mov)
    bh = np.insert(bh, pos_fin, mov_bh)
    if bh[-1] == 0:
        bh[-1] = 1
    
    new_pos_lb = [dp, bh]
    new_pos_fit = np.random.randint(20, 100) # metodo calcular_fitness()
    
    if new_pos_fit < min(fit_lideres): # Comparar con alpha
        manada[ind] = lobos_lideres[0] # anadir alpha a la manada
        fit_manada[ind] = fit_lideres[0]
        
        lobos_lideres[0] = new_pos_lb
        fit_lideres[0] = new_pos_fit
        break # ?
    elif new_pos_fit < fit_manada[ind]: # Comparar con posicion actual
        manada[ind] = new_pos_lb
        fit_manada[ind] = new_pos_fit

In [17]:
fit_lideres

[21, 26, 29]

In [20]:
lobos_lideres

[[array([4, 7, 2, 6, 3, 1, 5]), array([1, 0, 0, 0, 1, 0, 1])],
 [array([4, 5, 1, 3, 2, 7, 6]), array([0, 1, 1, 0, 1, 1, 1])],
 [array([1, 4, 7, 3, 6, 5, 2]), array([0, 0, 0, 0, 0, 0, 1])]]

In [18]:
manada

[[array([4, 1, 5, 2, 3, 7, 6]), array([0, 1, 1, 1, 1, 1, 1])],
 [array([2, 4, 6, 7, 3, 1, 5]), array([1, 0, 1, 0, 0, 0, 1])],
 [array([5, 7, 4, 2, 6, 3, 1]), array([1, 0, 1, 0, 1, 1, 1])],
 [array([3, 4, 7, 1, 2, 6, 5]), array([1, 1, 1, 0, 0, 1, 1])],
 [array([7, 4, 6, 2, 1, 5, 3]), array([0, 1, 1, 1, 0, 0, 1])],
 [array([7, 6, 4, 5, 2, 1, 3]), array([1, 1, 0, 0, 0, 0, 1])],
 [array([4, 3, 2, 6, 7, 1, 5]), array([1, 0, 1, 1, 1, 0, 1])]]

In [19]:
fit_manada

[31, 42, 70, 25, 53, 82, 65]

### Comportamiento de ataque

```
da = num_dptos * theta_2
for lobo in manada:
    if rand < 0.5:
        lider = alpha
    elif rand < 0.75:
        lider = beta
    else:
        lider = delta
    
    d = calcular_distancia(lobo, lider)
    
    while d > da:
        lobo = reducir_distancia(lobo, lider)
        d = calcular_distancia(lobo, lider)
```

In [22]:
da = np.floor(n_dptos * theta_2)
da

3.0

In [40]:
def seleccionar_lider():

    rand = np.random.random()
    if rand < 0.5:
        lider = lobos_lideres[0] # alpha
    elif rand < 0.75:
        lider = lobos_lideres[1] # beta
    else:
        lider = lobos_lideres[2] # delta
    
    return lider

In [59]:
def calcular_dist(elem_lobo, elem_lider):
    
    dist = 0
    for ind in range(len(elem_lider)):
        if elem_lider[ind] != elem_lobo[ind]:
            dist += 1
    
    return dist

In [60]:
def reducir_dist(elem_lobo, elem_lider, index):
    
    dp = np.arange(1, n_dptos+1)
    
    for i in dp[index:]:
        lid_val = elem_lider[i-1]
        lb_val = elem_lobo[i-1]
        if lid_val != lb_val:
            p_cambio = np.where(elem_lobo == lid_val)
            elem_lobo[i-1] = lid_val
            elem_lobo[p_cambio] = lb_val
            
        return elem_lobo, (i-1)

In [72]:
# Prueba de los metodos
lb1 = np.array([4, 6, 5, 7, 3, 2, 1])

In [73]:
# Seleccionar lider
lid = seleccionar_lider()
lid

[array([4, 7, 2, 6, 3, 1, 5]), array([1, 0, 0, 0, 1, 0, 1])]

In [74]:
# Calcular distancia
distancia = calcular_dist(lb1, lid[0])
distancia

5

In [75]:
# Reducir distancia
lb, ind = reducir_dist(lb1, lid[0], 0)
print(lb)
print(ind)

[4 6 5 7 3 2 1]
0


In [37]:
if d == da:
    print(True)

True


In [42]:
lb = manada[0][0]
lb

array([4, 1, 5, 2, 3, 7, 6])

In [44]:
p_val = np.where(lb == 4)
p_val

(array([0], dtype=int64),)

In [45]:
lb[p_val]

array([4])

In [46]:
lb1 = np.array([4, 1, 5, 2, 3])
lb2 = np.array([4, 5, 2, 1, 3])

In [49]:
diff = lb1 - lb2
diff

array([ 0, -4,  3,  1,  0])

In [51]:
p_diff = np.where(diff != 0)
p_diff

ValueError: either both or neither of x and y should be given